export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div style={{ background: 'red', color: 'white', padding: 10}}>Testing</div>
        {children}
        </body>
    </html>
  )
}
